dist: Bionic

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#    - os: osx
#      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - source ci/travis/install-${TRAVIS_OS_NAME}.sh

script:
  - mkdir build && cd build > /dev/null 2>&1
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION} -DTARGET_CPU=${TARGET_CPU} -DENABLE_UNIT_TESTS=ON ../
  - make
  - file ./bin/tcpping
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then objdump -af ./bin/tcpping; fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then objdump -section-headers ./bin/tcpping; fi;
  - make test
  - ./bin/unit_tests

after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"